### ISSUE TITLE
Does this method apply to linear regression models like elastic net?

### ISSUE THREAD

**Issue by albert-ying** [YyzHarry/imbalanced-regression#11]
Hi, I'm wondering whether I can use this method as a preprocessing step for non-DNN models, namely simple linear regression or elastic net regression? If so, how should I adopt this method?

Thank you so much!

**Comment by YyzHarry** [comment]
Hi, thanks for your interest! Yes, for LDS, since it operates on the label space, it is independent of the model you use. You can refer to [our tutorial](https://github.com/YyzHarry/imbalanced-regression/tree/main/tutorial) for a quick starting, where you only need to replace the NN model with whatever regression model you like.

As for FDS, it might be less straightforward; but since it only needs feature statistics, if the algorithm can generate intermediate features for each input, it can also be adapted, depending on the actual method you use.

**Comment by albert-ying** [comment]
Thank you so much! I will close this issue for now!
