### ISSUE TITLE
validation question

### ISSUE THREAD

**Issue by namasang1** [YyzHarry/imbalanced-regression#19]
hello, I read your paper interestingly and want to apply it to my custom data.
In this regard, two problems occurred.

first, when i evaluate my custom data, i can suffer this error
![1](https://user-images.githubusercontent.com/86755120/153804615-1774de8e-2b97-4375-824e-e886e952b9a7.JPG)
do you know what is?

And can i extract each prediction results, not average prediction result?. 

thank you

**Comment by kaiwenzha** [comment]
Hi @namasang1 Thanks for your interest. It seems that the error was raised because the `low_shot_gmean` list is empty, which indicates that there is no low-shot label under the current low shot threshold. You may change the many/medium/few shot thresholds (check `many_shot_thr` and `few_shot_thr` parameters in the following code) according to your data. 
https://github.com/YyzHarry/imbalanced-regression/blob/055a7b3804bbaf903ed25a55c11ab8acc6e142e1/agedb-dir/train.py#L338

Sure, you can extract each prediction result without averaging. `preds` in the following code is a list that saves all the prediction results. You can directly use it without applying `shot_metrics()` function to get averaged results.
https://github.com/YyzHarry/imbalanced-regression/blob/055a7b3804bbaf903ed25a55c11ab8acc6e142e1/agedb-dir/train.py#L325
