### ISSUE TITLE
Question for Algorithm 1

### ISSUE THREAD

**Issue by Nate1874** [YyzHarry/imbalanced-regression#2]
Hi, I have a question for the pseudo code in Supplementary A section. 

For the Algorithm 1, the LDS is only used to compute the weights for loss inverse re-weighting scheme. Why not use the smoothed labels to train the models if LDS captures the real imbalance that affects regression problems? 

In addition, could you provide code for computing the effective label density distribution?

Thank you.

**Comment by YyzHarry** [comment]
Hi - thank you for your interests!

For LDS, we are estimating an effective label density distribution, so it is the label density (distribution) rather than label itself that is smoothed. As you noted, the effective density estimated by LDS is independent of which method you use -- a straightforward adaptation can be the re-weighting scheme; we also apply the estimated density to some classic methods and show improvements (see Sec. 4 baselines, "Synthetic samples" for example).

The code will be released very soon (in coming weeks). Please stay tuned!

**Comment by YyzHarry** [comment]
Hi @Nate1874 - the code has been released. Let me know if you have any questions!
